### ISSUE TITLE
Add General Config to S3 bucket

### ISSUE THREAD

**Issue by Gujarats** [traveloka/terraform-aws-s3-bucket#2]
## Here is some list of configuration that we can add to the S3 bucket: 
- Add cloudfront for our s3 bucket so the object can be read publicly with private S3 bucket
- make our S3 bucket private
- use encryption as default (already in the module)
- versioning disable as default (can be change via variable)
- S3 bucket for cloudfront logs

Please add more configuration if you think it can be use as general use case

**Comment by Gujarats** [comment]
cc @sumodirjo @rafikurnia @nin9swells

**Comment by rafikurnia** [comment]
Hi @Gujarats 
Can you please elaborate what do you mean by `configuration we can add to the s3 bucket` ?

**Comment by aoktox** [comment]
> * Add cloudfront for our s3 bucket so the object can be read publicly with private S3 bucket

Hi @Gujarats i think there is no additional config needed in S3 bucket when you use Cloudfront in as its CDN. 

CMIIW

**Comment by rafikurnia** [comment]
> - Add cloudfront for our s3 bucket so the object can be read publicly with private S3 bucket

This is a general S3 module, neither CloudFront nor S3 for CloudFront module

> - make our S3 bucket private

You can set it using this variable, or leave the default value: https://github.com/traveloka/terraform-aws-s3-bucket/blob/89d4b97c6fb669ae97e3523bb8d2acbcbee1ea76/variables.tf#L26-L30

> - use encryption as default (already in the module)

Yep, already in the module https://github.com/traveloka/terraform-aws-s3-bucket/blob/89d4b97c6fb669ae97e3523bb8d2acbcbee1ea76/main.tf#L17-L23

> - versioning disable as default (can be change via variable)

Also yep: https://github.com/traveloka/terraform-aws-s3-bucket/blob/89d4b97c6fb669ae97e3523bb8d2acbcbee1ea76/main.tf#L25-L27

> - S3 bucket for cloudfront logs

This one is handled by our scaffolding
